### ISSUE TITLE
Create Basic Event View

### ISSUE THREAD

**Issue by mikemadison13** [Drupal4Gov/Drupal-GovCon-2017#102]
We want a basic view to be a part of the event feature (see https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/16) that will show upcoming events. This should be committed into the drupal-cod/event feature.

- [ ] Added Upcoming Events View (only published, future events)
- [ ] Added Events Archive View (only published, past events)
- [ ] Changes submitted to drupal-cod
- [ ] Changes (if any) submitted to DGC repo

**Comment by aweingarten** [comment]
@mikemadison13 

Tried setting up OG.  Had some issues: 
1: Event Doesn’t have og 
2: After enabling OG on event got error:
```
The website encountered an unexpected error. Please try again later.

Drupal\Core\Entity\EntityStorageException: 'og_role' entity with ID 'node-event-non-member' already exists. in Drupal\Core\Entity\EntityStorageBase->doPreSave() (line 425 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).
```
After reloading the issue went away.  

3. One I added an OG to basic page locally.  I noticed that  the Groups audience Needs a dropdown.  Also need a way to set a default.  Also need a way to probably pass the OG via referrer. so that
