### ISSUE TITLE
Install OG

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#16]
- [x] Add Dependency for drupal-cod/event
- [x] Create basic Event Content Type (that is a Group using OG) within https://github.com/drupal-cod/event namespace
- [x] Basic Fields setup as defined below

**Fields**
* Title
* Body
* Date
* Image

**View**
* Basic list of events
* Basic calendar of events

**Comment by mikemadison13** [comment]
see my PR here: https://github.com/drupal-cod/event/pull/1

**Comment by mikemadison13** [comment]
and PR here: https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/101

**Comment by mikemadison13** [comment]
a quick update: 

OG itself seems to work with the CMI (not with Features). However, on BLT projects when the CMI import happens, the config stored in the config/install folder of the event module doesn't work (it works fine after performing a pm-uninstall / en). So, this may be problematic for projects relying on BLT. I will continue to dig on this. My hunch is that a feature would not have this problem.

Calendar is functional, but doesn't seem to support end date functionality (yet). So if we have a calendar, we can have the "start" date of an event, but we cannot have the full date span (yet). Any opinion on that @aweingarten for the time being?

Otherwise I think we can get this POC constructed as above, it just won't work properly with a BLT project if we rely on the config/install model

**Comment by mikemadison13** [comment]
see PR for this on the drupal-cod/event space https://github.com/drupal-cod/event/pull/1
