### ISSUE TITLE
Port the ticket Module to D8

### ISSUE THREAD

**Issue by aweingarten** [Drupal4Gov/Drupal-GovCon-2017#20]
## Business Requirements

() As a user I want to register to attend the conference.
() As an admin I can create ticket types and specify a number of tickets for each ticket type.
() Once the number of registrations exceeds the number of tickets for that type users can no longer register for that ticket type.
() Right now the workflow is that an anonymous user can register on the site as a new drupal user
() then they can request some number of free tickets from a finite pool of tickets
() One user can register for different ticket types.
()  As a user I want to be able to register others for a ticket to govcon
() As a user I want to be able to cancel my ticket registration to govcon
() As an administrator I want to be able to cancel tickets registration for the event.
() As an administrator I want to be able to export tickets.
## Technical Requirements

() Port the ticket module to D8 https://www.drupal.org/project/ticket

**Comment by timwood** [comment]
What about the following items (sourced from the GovCon D8 Planning document)?
1. As a user I want to be able to register others for a ticket to govcon
1. As a user I want to be able to cancel my ticket registration to govcon
1. As an administrator I want to be able to cancel tickets registration for the event.
1. As an administrator I want to be able to export tickets.

**Comment by fluxsauce** [comment]
BADCamp has an unlimited number of free tickets, but we do have optional sponsorships at X levels (typically, $25, $50, $100). The workaround would be having a insanely high number of tickets of each type.

* [ ] As a user, I want a free ticket by registering an account
* [ ] As an administrator, I want a user's ticket to be canceled if their account is deleted
  * Ex: Deleting spammer
* [ ] As a user, I want to be able to purchase a free ticket (if the price is `0.00`) without providing payment information
* [ ] As a user, I want to be able to upgrade my ticket and pay the difference
* [ ] As a user, I want to be able to downgrade my ticket and receive the difference
* [ ] As a user, I want to receive a receipt when I acquire a ticket
* [ ] As a user, I want to review my ticket activity on the site
* [ ] As a user, I want to be able to purchase multiple tickets for different parts of the event
  * Example: Training
* [ ] As an administrator, I want to mark a ticket as used
  * With BADCamp sponsorships, you receive swag based on your sponsorship level; we want to ensure that someone doesn't double-dip

**Comment by Nouveau** [comment]
@fluxsauce I don't think our user requirements should specify how we meet the user needs. "As a user I want to register to attend the conference for free." is better than "As a user, I want a free ticket by registering an account"

Here's my updated list:

As a user I want to register to attend the conference.
As a user I want to be able to register others for a ticket.
As a user I want to be able to cancel my ticket registration (If I want a refund I will need to request this from conference organizers).
As a user, I want to be able to purchase a free ticket without providing payment information.
As a user, I want to receive a receipt via email when I acquire a ticket.
As a user, I want to review my ticket history on the site.

Not MVP in my opinion: As a user, I want to be able to upgrade my ticket and pay the difference.
Not MVP and I think this one could be undesirable for a number of conferences because of budget planning: As a user, I want to be able to downgrade my ticket and receive the difference.

As an administrator I need to be able to create ticket types and be able to specify a number of tickets for each ticket type (or leave unlimited).
As an administrator I need to be able to specify a start time and end time for ticket sales.
As an administrator I want to be sure that users cannot register for a sold-out ticket type. 
As an administrator I want to be able to cancel a ticket.
As an administrator I want to be able to export ticket records to a csv file.
As an administrator, I want to give an individual user an easy way to redeem a pre-purchased ticket.
As an administrator, I want to track the history of a ticket (pending, canceled, purchaser, etc.).
As an administrator, I want to mark a ticket as checked-in.

**Comment by timwood** [comment]
How about adding the following. This is how it's done in COD 7.x today. The ticket entity contain some of the registration information. 

As an administrator, I want to add additional fields per ticket type to track dietary needs, t-shirt size, collect name, affiliations and more.
