### ISSUE TITLE
Create Custom 403 Page

### ISSUE THREAD

**Issue by charlieartist** [Drupal4Gov/Drupal-GovCon-2017#301]
To fulfill a critical UX need, and extend the style of the Website, a custom 403 Access Blocked page is needed. As with the rest of the site, this will need to be responsive, and accessibility-compliant.

**Comment by jonraedeke** [comment]
@charlieartist Can we make this and the 404 page the same component and just swap out content when we implement?

**Comment by charlieartist** [comment]
@jonraedeke How should we accomplish this.

**Comment by jonraedeke** [comment]
@charlieartist I thought since this one has some of the same classes and the pages are very similar to just make one component and swap out the json data to change the message and image to make it a 404 or 403 page. I think I made a suggestion similar to this on the 404 page pull request. See https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/302

**Comment by charlieartist** [comment]
@jonraedeke Thanks--you know this far better than I do. How difficult is it to accomplish?
