### ISSUE TITLE
Conf reg (ticket): State field no good

### ISSUE THREAD

**Issue by alisonjo2786** [Drupal4Gov/Drupal-GovCon-2017#310]
### Requirements

- [x] Add US territories to State select options. (see below for what to add) add a "--" after Wyoming, and then add the territories listed below
- [x] rename State/Province label to just _State_
- [x] remove Zip field
- [x] Put Country as first field in the field
- [x] let the ~~address,~~ city, and state fields be conditional. they only show up if you select United States from the Country list.
- [ ] Require fields

#### Background
The states option-list only includes 50 states + DC -- no other US territories, let alone "provinces" (regardless of what the field label claims :) ).

While it would be nice to have different conditional options for countries outside the US, I'm not sure we have the bandwidth for that this time around.  What events.drupal.org does with conditional country selection is nice.  For this event, it would be nice to know where in the US people are coming from - and if not US, what country. That's enough for now.

####  US Territories to be added to State select list:
Armed Forces (Americas)
Armed Forces (Europe, Canada, Middle East, Africa)
Armed Forces (Pacific)
American Samoa
Federated States of Micronesia
Guam
Marshall Islands
Northern Mariana Islands
Palau
Puerto Rico
Virgin Islands

**Comment by alisonjo2786** [comment]
@aweingarten High priority

**Comment by lkopacz** [comment]
@alisonjo2786 @jdearie,

I'm seeing a couple of conflicts in this ticket with https://github.com/Drupal4Gov/Drupal-GovCon-2017/issues/286.

1.  The reason that the Country field isn't first is because it wasn't easily done in config. I tried to manipulate it in the YAML settings (vs the normal Webform UI settings), and it appeared to not work. I should have clarified that in the original ticket. I was under the impression it was a "Nice to Have." If that is still the case, it should be left alone. 
2.  I thought that we weren't including the Address fields. Is that different?
3.  If you want to add those states, you can add them through config. Warning (as I learned the hard way), this is not transferrable using Config. You MUST add them manually using the path below.  /admin/structure/webform/settings/options/manage and edit the states list. 
4.  My way around United States not being the top of the list was making it a default value, which makes conditional logic tricky/pointless.  I suggest we either do one or the other here. It seems that there would need to be a little research on my end at least on the conditional logic portion (not very UX-y to me). It seems possible in the UI, but buggy and/or not intuitive.

**Comment by alisonjo2786** [comment]
Thanks, @lkopacz !

The address field thing was that we're only collecting city, state, country ( #213 ).  I don't even remember putting that fourth check box task (the conditional stuff), I can't be positive but my guess is that someone else chimed in and added it as an attempt to try to help flesh out the details -- but definitely completely unnecessary!!  Please just remove that task item (I can't do much editing from my phone, or I can't figure out how to do much editing from my phone).

I'm fine with United States not being selected by default, totally just a "nice to have" for me, and thank you!  (Having it selected by default is also cool, but really nbd if it creates other issues.)

States field: I don't know what do do -- I definitely want to add those options, but like, we have international ppl, and it's a required field, so those folks simply won't be able to fill out this form :-/  i feel like I said this before but maybe not -- does webform allow or do we already have an add-on that allows "select or other" fields?  I think I've seen it on a couple of our other registration form fields...?  I think that's what we should do here -- all the US states/territories, plus "Other" > Text box.  If that's not practicable (if we can't do it without a hacky implementation), then I guess we should just have a generic "other" field, but that's kinda a bummer.  (I guess we could add help text like, "If "other," include your state abbreviation in the City text box." .....?)

Cc @jdearie

**Comment by timwood** [comment]
@alisonjo2786 Looks like the webform uses some implementation of the Address field/module. So in webform we add one field and then it has items within it that field (Country, state, city, street, etc.) which can be enabled/disabled, marked as required and marked as visible/hidden. There is no option to reorder (as @lkopacz mentioned) and very little flexibility with each sub-item/field. There is also no ability to enable the "Other" option as some other fields have or do conditional.

It may be that since the overall Address field is not required, the required checkboxes for the individual address components aren't having the affect they should, which may actually be a blessing here if we want to keep City, State and Country, but it could also be confusing for international users since the individual address components are marked as required.

Why not just mark all address components not required?

**Comment by timwood** [comment]
<img width="590" alt="screen shot 2017-04-23 at 5 53 43 pm" src="https://cloud.githubusercontent.com/assets/91050/25317790/dae1ecd4-284d-11e7-8789-f6b075eb94e9.png">

**Comment by timwood** [comment]
Closed with #344. Extra options added to States list, label updated to just "State" and all fields are no longer required.

**Comment by bheatonf1** [comment]
'Other' can be made an option by changing the form field to a 'select other' field. 
Fields can be reordered by adding a form_alter and targeting the subfield via a postpended __weight to the subfield #property. We can also do _some_ things with #states visibility/invisibility but it is a bit jankey and seems to only work on individual fields.

**Comment by timwood** [comment]
@bheatonf1 Great info, thanks! Want me to reopen this (just closed it) and keep assigned to you for those enhancements?

**Comment by bheatonf1** [comment]
I did not keep the Address fields on this. Not sure if we desire them. I kept Country, City and State.

**Comment by bheatonf1** [comment]
@timwood sure - I have a pretty good handle on how to target these subfields now - wasn't easy or documented :(

**Comment by bheatonf1** [comment]
@timwood I just added a PR for this work if you want to take a look at what I've done to  make most of the above possible.

**Comment by timwood** [comment]
Reopened for last two checkbox items (and any other suggestions @bheatonf1 wants to tackle!).

**Comment by timwood** [comment]
I'm removing go-live triage since the changes made by @lkopacz make this acceptable for launch, in my opinion.

@bheatonf1 Be sure to pull down latest code and grab fresh DB.

**Comment by timwood** [comment]
@bheatonf1 I pulled down the PR and tested locally. Looks good except two issues:

1. When selecting a different country (other than the default "United States", all address fields disappear!
2. My changes from #340 were reverted.

Thanks for adding the extra territories back, and I think it's better that they are in the bottom of the list with a separator (although this seems to make the separator an option that validates).

**Comment by alisonjo2786** [comment]
@bheatonf1 No Street address and zip at all, right? Just wanted to double check.

**Comment by timwood** [comment]
Correct, @alisonjo2786.
![image](https://cloud.githubusercontent.com/assets/91050/25345076/00a6dc92-28e2-11e7-988a-cfa59fa3281f.png)

**Comment by bheatonf1** [comment]
Hi @timwood got it. Checking out the issues today.

**Comment by jdearie** [comment]
Let's make sure we keep these fields required. I know you're still working on this, but the version on dev doesn't have the address fields required... and I wanted to make sure we know they need to be required. Thanks!

**Comment by timwood** [comment]
@bheatonf1 http://timonweb.com/posts/set-required-and-optional-address-inputs-for-address-field-in-drupal-8
